on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        # Navigate to the project directory
        cd /var/www/backendOnu
        sudo chown -R $USER:$USER /var/www/backendOnu

        
        # Update the repository
        git pull
        
        # Install Node.js dependencies
        npm install --production
        
        # Ensure PM2 is installed globally
        npm install pm2@latest -g
        
        # Start or restart the application using PM2
        pm2 reload ecosystem.config.js || pm2 start ecosystem.config.js
        
        # If you do not have an ecosystem.config.js, you can use the line below instead:
        # pm2 restart all || pm2 start app.js --name "backendOnu"
        
        EOF
